### ISSUE TITLE
[Feature] [Change] Vertical scroll bar on iOS

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#72]
**Description**
On iOS, it's possible to tap on and drag the vertical scroll bar to quickly scroll through long pages. Cryptee seems to disable the scroll bar, and scrolling through long documents can be a pain because of it.

**Solution**
I'd just like the vertical scroll bar! I can imagine a future where the header list available on desktop devices is available on mobile and support this kind of whole-doc scrolling, but in the meantime just a regular scroll bar would be really helpful.

**System Information:**
 - Device: iPhone 6s
 - OS: iOS 13.4.1
 - Browser Safari–PWA installed to home screen

**Comment by johnozbay** [comment]
Hi there! 

This is an excellent point! 
I'm working on some layout changes (now that there's tables, I'm trying to make sure everything fits as expected both vertically & horizontally with ultra-wide tables) 

Added this to my list, and will do my best to add this in as quickly as possible.

For others who might run into this issue some day in the future – _this fix will only address scrollbar issues on mobile, and not desktop yet_ – more on this below.

---

Part of the reason why I had to disable vertical scrollbars in the first place is because every OS has a different scrollbar behavior, and worse, every browser has a different scrollbar width.

So for example on Macs & iOS, scrollbars are displayed over the content, they're thin, and they disappear when they're not in use. All browsers on these two platforms use the system settings. 🎉

But on windows & linux, the situation is a complete nightmare. 🔥
Chrome & Edge uses one logic & width – Firefox another. 

Scrollbars are wider (across different OSes & browsers), and they're displayed in a way that blocks over the content. 

So if you need to make use of corners, i.e. where Cryptee's save button & dropdown button is on the document for example, the scrollbar ends up blocking the button entirely. (even when it's not in use / disabled) Or if you're scrolling through files in folder etc.

And because it's over the content & blocking it, and there's no way to override the behavior via css other than making the entire container un-scrollable, the only solution is to hide all scrollbars entirely, by adding an extra 20px padding, and nesting the scrollable element in an `overflow:hidden` container.

https://github.com/cryptee/web-client/blob/51cd8bc43216f18a612a9cdab0a40a4dd146fa28/source/css/docs.css#L2617-L2620

To add insult to the injury, [Edge and Firefox have different widths of scrollbars and entirely different behaviors on Windows](https://stackoverflow.com/questions/33773216/why-is-edge-body-scrollbar-different-from-firefox-body-scrollbar/33773787). So you have to add `-ms-overflow` overrides in CSS to make Edge behave similar to Firefox, but you can't change the width to match Firefox. 🤦🏻‍♂️

And to add more fuel to the fire, there's also the problem of touch-screens & stylus-support on Windows & Linux laptops & tablets. They dynamically change the width of the scrollbar to make it easier to click or tap, as soon as the device detects a stylus on the screen, (or when user switches to tablet mode by touching the screen) but – since scrollbars are blocking/hiding content, and the behavior is inconsistent between browsers, ( and even OS versions in some cases ) it becomes an even bigger nightmare to lay things out in a way that makes logical sense. 

To deal with this exact problem, web-apps like Google Docs use custom-built scrollbars instead of relying on the OS & browser's own scrollbars. And I think sadly we'll need to follow this approach too, but needless to say it's a big undertaking, and it's taking time.
 
One of these days w3c should introduce a web standard for scrollbar widths & behaviors. 
It's hell on earth right now. 😅

**Comment by BasilTomato** [comment]
As far as I can see this is resolved in 3.0, tested Windows Edge and Android Bromite browsers.

**Comment by dhda** [comment]
Not resolved on iOS yet (tested on iPhone 6s running iOS 14.4). The vertical scroll bar is visible now (🎉) but it’s still not possible to tap and drag on the scroll bar for fast scrolling. Tapping on the scroll bar now kind of just freezes the element for a few seconds and prevents any further scrolling or input until the scroll bar fades out, and then everything returns to normal.

Having a scroll bar in other places like the document list and the table of contents would also be useful. It’d also be great to be able to tap the top bar of the screen to scroll to the top of a document (not sure if that one is a PWA restriction or not).

**Comment by johnozbay** [comment]
We're looking into what's causing the issue on iOS, since we're using native scrolling with no margins. It should show up, and should be possible to tap and scroll quickly. Chances are iOS has a CSS Grid rendering quirk causing this. We'll figure it out and fix it ASAP. 

Also related to #58 and #99, since once we introduce zoom in / out for print-layout, we're considering using a custom scrollbar (and not a native one) to make scrolling better for multi-page & zoomed layouts.

**Comment by dhda** [comment]
I was actually able to successfully drag the scroll bar once but I have no idea what I did to get that to happen. Another weird thing I noticed is that tapping in the margin where the scroll bar would appear, even when it’s not visible, still causes the document to freeze up for the same amount of time.

Edit: ah, figured it out. Tapping on the far right edge of the screen causes the freeze, regardless of the scrollbar. There’s actually a very narrow band a few mm away from the right edge of the screen where it’s possible to grab the scrollbar. I can get it to work by aiming my tap just a tiny bit to the left of where the scrollbar actually is.

**Comment by johnozbay** [comment]
> ah, figured it out. Tapping on the far right edge of the screen causes the freeze, regardless of the scrollbar. There’s actually a very narrow band a few mm away from the right edge of the screen where it’s possible to grab the scrollbar.

Super good catch! Sounds like there's an unintentional overflow or z-index problem somewhere. We'll get this sorted out right away.

**Comment by dhda** [comment]
One other thing that might be helpful is that it happens in portrait orientation, but not in landscape.

**Comment by dhda** [comment]
With the context of #105, I can confirm that the issues in this ticket are all present in both Standard and Zoomed display modes.

**Comment by johnozbay** [comment]
Ever since we closed #99, we've been trying to figure out what's wrong with iOS's scrollbars, because _it definitely should work now_. So here's what we know so far. 

1 – There's an iOS WebKit bug that makes scrollbars invisible when your device is in dark mode. 
https://bugs.webkit.org/show_bug.cgi?id=213394
good job apple. way to fuck the web🤦🏻‍♂️ 

So here's a screenshot with both iOS and Cryptee Docs set to `light-mode` (you can see the scrollbar is visible)

<img src="https://user-images.githubusercontent.com/611338/123937891-4ffde980-d99f-11eb-8c2e-9d1afdd5c444.jpg" width="320">

And here's the same document, same position in document, with Cryptee set to `light-mode` but iOS set to `dark-mode`:

<img src="https://user-images.githubusercontent.com/611338/123938218-95bab200-d99f-11eb-820c-4ba6d775e913.jpg" width="320">

---

So we thought "oh great! we can then simply style the scrollbar or force/fake a 'light mode', and solve this problem. "

2 – To add insult to the injury, iOS 14 apparently removed custom CSS styling for scrollbars, but didn't really document it anywhere. 🤦🏻‍♂️
https://developer.apple.com/forums/thread/670065

---

To summarize, as of #99, 

– With iOS `light-mode` and Cryptee `light-mode`, (or with  iOS `dark-mode` and Cryptee `dark-mode`) the scrollbar is visible and tappable, so you can (should be able to), tap, hold and scroll faster as expected. 

– With iOS `dark-mode` and Cryptee `light-mode` or vice versa however, you'll just have to try to _feel_, _sense_ and _predict_ where the scrollbar is. Because iOS seems to override everything. And if like us, and the rest of humanity, you couldn't sense where the scrollbar is ... ~[it might be because we're all holding our phones the wrong way](https://www.engadget.com/2010-06-24-apple-responds-over-iphone-4-reception-issues-youre-holding-th.html)~. 😂

---

For now I'll close this, since it depends on a bunch of external dependencies, and there's not much more we can do about it. However, if you have any ideas for workarounds / anything changes etc, please feel free to comment / re-open this thread. ✌🏻 Thanks a lot for your patience with all this.
