### ISSUE TITLE
[Bug] extra new line after each line if pasted into an external program

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#87]
**Describe the bug**
If I try to paste the content copied from a Cryptee document into an external program there is an unnecessary extra new line after each line pasted. This is quite annoying and have to be fixed each and every time.
The problem is observed in following situations:
- Android: text pasted into chat app, or any other app
- Windows: text pasted into Notepad++, and possible other app

**To Reproduce**
Steps to reproduce the behavior in Windows:
1. copy any multi-paragraph text from a Cryptee document
2. paste the content into a file opened with Notepad++ (and possible any other app)

**Expected behavior**
No extra new line after wach line pasted.

**Screenshots**
n/a

**System Information (please complete the following information):**
 - Device: Android smart phone, Windows laptop
 - OS: Android 10, Windows 10
 - Browser: Android: Ungoogled Chromium; Windows: Firefox, Chrome
 - Browser Version: latest
 - Browser Extensions / Add-ons / Content Blockers: disabled
 - Do you have any DNS-based content blockers? no
 - Are you on a managed network? no

**Additional context**
n/a

**Comment by johnozbay** [comment]
Hi there! 
Today we released Cryptee v3.0, and it's a completely rewritten, entirely new app. We fixed a ton of bugs in copy / pasting, and added a bunch of new features like detecting insecure urls / image trackers while pasting. ( 01edfe4 ) You can read more about this update here : 

https://blog.crypt.ee/say-hello-to-a-new-cryptee

Give it a try and let me know if this update fixes the bug! 

Thanks for this! ✌🏻

**Comment by BasilTomato** [comment]
Hello, thanks for the update!

I have tested in 3.0, and this problem still exist.

**Comment by jebbster88** [comment]
I assume that's down to Cryptee treating each line as the start of a new paragraph. Try pasting the text below into notepad and I'd wager you get the same result, it'd be the same case copying paragraphs from any website.. I'm not surprised it behaves this way, and to be honest appreciate it. I think where Cryptee possibly falls down is the inability to use Shift-Return to insert a soft line break (as per the last part of my example below), but that's not Cryptee's fault (https://github.com/quilljs/quill/issues/252)

### Example

<p>This is a paragraph</p>
<p>This is another paragraph</p>
<p>This is all one paragraph<br />with a line break</p>


### Example source
```
<p>This is a paragraph</p>
<p>This is another paragraph</p>
<p>This is all one paragraph<br />with a line break (soft break)</p>
```

**Comment by johnozbay** [comment]
Hey all 👋🏻 

Thanks a million for your patience with us for all these years! 

We've been working on a massive overhaul for our editor this year. 
It took us a long time but we're finally ready, and this is now fixed this in the alpha version and the issue is linked to our internal issue/release tracker.

Once the update with this fix is out (should be in a couple of days once we're done testing everything), this issue will be closed automatically, and you'll get a notification! Holy cow it feels good to close this issue after years. 

Thank you so much for filing this, your help and patience!

Best,

J
